<center> <h2 Style="background-color:orange; color:black"> <br> Numpy <br> </h2>

In [ ]:
# Numpy Numerical Python for supporting multidimensional arrays
# pip install numpy

In [1]:
import numpy

In [2]:
# create an array  (1D)
A1=numpy.array([1,2,3,4,5])
A1

array([1, 2, 3, 4, 5])

In [3]:
numpy.square(A1)

array([ 1,  4,  9, 16, 25])

In [5]:
import numpy as np

In [6]:
# create an array  (2D)
A2=np.array([[1,2,3],[4,5,6]])
A2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
A1.shape

(5,)

In [11]:
A1.size

5

In [12]:
A2.shape

(2, 3)

In [14]:
A2.size

6

In [15]:
A3=np.array([1,2,3,4,5,6])

In [16]:
A3

array([1, 2, 3, 4, 5, 6])

In [17]:
A3.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
A1

array([1, 2, 3, 4, 5])

In [19]:
A1[0]

1

In [20]:
# slicing
A1[1:4]   index[start:end]   elements will be start to end-1

array([2, 3, 4])

In [21]:
# index[start:end:step] 
A1[:4]

array([1, 2, 3, 4])

In [22]:
A1[0:]

array([1, 2, 3, 4, 5])

In [23]:
A1[1:6:2]

array([2, 4])

In [24]:
# Negative Index for slicing from the end
A1[-4]

2

In [25]:
A1[-1:]

array([5])

In [27]:
A1[-4:-1]  

array([2, 3, 4])

In [28]:
A1[:-1]

array([1, 2, 3, 4])

In [29]:
A1

array([1, 2, 3, 4, 5])

In [30]:
# reverse print
A1[::-1]

array([5, 4, 3, 2, 1])

In [31]:
A4=np.full((3,3),2)

In [32]:
A4

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [33]:
# First row
A4[0,:]

array([2, 2, 2])

In [34]:
# second column
A4[:,1]

array([2, 2, 2])

In [36]:
A4[:2,:2]

array([[2, 2],
       [2, 2]])

In [38]:
A1[1,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [39]:
A4[0,:]

array([2, 2, 2])

In [40]:
A4[1,:]

array([2, 2, 2])

In [42]:
# second row and first column
A4[1,0]

2

In [43]:
np.max(A1)

5

In [ ]:
mean, median, std, var, min

In [44]:
np.sort(A1)

array([1, 2, 3, 4, 5])

In [45]:
A1[::-1]

array([5, 4, 3, 2, 1])

In [46]:
A5=np.array([[3,1,2],[9,7,8],[6,4,5]])

In [47]:
A5

array([[3, 1, 2],
       [9, 7, 8],
       [6, 4, 5]])

In [48]:
np.sort(A5)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [49]:
np.sort(A5, axis=1) #axis=1 row wise

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [50]:
np.sort(A5, axis=0)  #axis =0 means column wise

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

In [53]:
np.sort(A5)[::-1]  # Descending order since slicing operation reverses the order of the rows, it will not reverse the elements 

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [54]:
A5

array([[3, 1, 2],
       [9, 7, 8],
       [6, 4, 5]])

In [ ]:
# Matrix operations
# np.add(M1,M2)
# np.multiply(M1, M2)
# np.dot(M1,M2)
# M2=np.copy(M1)
# np.concatenate (M1,M2,axis)
# np.transpose(M1)
# np.trace